---

  - name: Install various packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop: "{{ krb5_packages }}"


  - name: Add krb5.conf
    template:
      src: krb5.conf.j2
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: 0644

  - name: Krb5 ticket renew
    ansible.builtin.cron:
      name: "krb5 ticket renew"
      minute: "0"
      hour: "3,11,19"
      job: "/usr/bin/kinit -k -t /etc/krb5.keytab {{ inventory_hostname|upper }}$ > /dev/null"
    when: krb5_renew_cron

