---

  - name: Install various packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop: "{{ krb5_packages }}"


  - name: Add krb5.conf
    template:
      src: krb5.conf.j2
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: 0644

  - name: Krb5 ticket renew
    ansible.builtin.cron:
      name: "krb5 ticket renew"
      minute: "0"
      hour: "3,11,19"
      job: "/usr/bin/kinit -k -t /etc/krb5.keytab {{ inventory_hostname|upper }}$ > /dev/null"
    when: krb5_renew_cron

  - name: Create systemd service file for krb5 ticket renew
    ansible.builtin.template:
      src: krb5renew.service.j2
      dest: "{{ service_file }}"
    notify:
       - Reload systemd
    when: krb5_renew_systemd

  - name: Create systemd timer file for krb5 ticket renew
    ansible.builtin.template:
       src: krb5renew.timer.j2
       dest: "{{ timer_file }}"
    notify:
        - Reload systemd
        - Enable and start krb5-ticket-renew.timer
    when: krb5_renew_systemd
