---
# handlers file for ansible-role-krb5

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start krb5-ticket-renew.timer
  ansible.builtin.systemd:
    name: krb5renew.timer
    state: started
    enabled: yes
